//
//  Article.swift
//  WufWuf
//
//  Created by Farras Doko on 06/08/20.
//  Copyright © 2020 wufwuf. All rights reserved.
//

import UIKit

var attributedString = NSAttributedString(string: "Katarak merupakan kerusakan pada lensa mata yang terjadi karena kerusakan sel atau membran protein, sehingga menyebabkan perubahan warna pada lensa mata berwarna putih seperti awan secara menyeluruh atau sebagian.\n\n", attributes: [.font:UIFont.boldSystemFont(ofSize: 17)])
var katarakPengertian: [Any] = [attributedString, "Hal ini menyebabkan mata sulit melihat karena cahaya tidak bisa masuk ke retina yang terhalang oleh lensa mata yang rusak. Jika katarak masih berukuran kecil, tidak akan terlalu mengganggu penglihatan, namun harus terus dipantau karena jika menjadi semakin tebal, kemungkinan akan menyebabkan kebutaan.\n\nAnjing yang terkena katarak masih bisa melihat, meskipun hanya melihat perubahan cahaya. Katarak tidak membuat rasa sakit, hanya saja memang mengganggu penglihatan. Namun jika peradangan berlanjut dapat terjadi glaucoma yang terasa sakit bagi anjing."]
let kPengertianMore = "\n\nFaktor keturunan (herediter) menjadi faktor utama terjadinya katarak, terutama pada ras-ras yang murni seperti Poodle, Cocker spaniels, Siberian husky, Maltese, Labrador, Golden retriever dan Yorkshire terrier."

let katarakPenyebab = ["1. Faktor genetik keturunan (herediter)\n2. Umur tua\n3. Penyakit rendahnya kalsium dalam darah (hipokalsemia)\n4. Penyakit diabetes mellitus.\n5. Inflamasi pada mata (uveitis)\n6. Obat-obatan tertentu (kortikosteroid)\n7.  Kontak dengan radiasi ultraviolet atau zat-zat beracun berbahaya\n8.  Luka traumatik/ benturan pada daerah mata\n9.  Luka terkena cairan kimia beracun yang mengenai mata.\n10.Radiasi sinar terlalu tinggi."]
let katarakGejala = ["1. Terdapat semacam kabut berwarna putih keruh/ abu-abu di mata\n2. Katarak kurang dari 30%, tidak ada gejala yang berarti.\n3. Katarak di atas 60%, mulai ada gangguan penglihatan\n4. Pada kasus penyebab diabetes mellitus ditandai dengan penurunan berat badan yang sangat drastis, seringkali buang air kecil, dan anjing mengalami peningkatan nafsu minum yang tinggi (anjing sering minum)"]

let pengertianBold = NSAttributedString(string: "Demodekosis pada anjing merupakan penyakit kulit yang disebabkan oleh infeksi tungau Demodex sp.\n\n", attributes: [.font:UIFont.boldSystemFont(ofSize: 17)])
var demodexPengertian: [Any] = [pengertianBold, "Demodex sp. merupakan fauna normal yang menetap pada kulit anjing. Infeksi demodekosis dapat terjadi pada anjing semua umur, khususnya pada anjing muda dan anakan sangat sering terjadi. Penularan tungau Demodex sp.ini dapat terjadi mulai dari anak anjing berumur tiga hari.\n\nPenularan penyakit demodekosis, dapat terjadi secara kontak langsung dengan anjing yang menderita demodekosis. Hewan penderita yang sering diserang pada usia anjing di bawah umur 1 tahun namun demikian pada anjing di atas umur 1 tahun banyak mengalami kejadian infeksi penyakit ini (Henfrey, 1990; Scott et al., 2001)."]
let dPengertianMore = "\n\nDalam kondisi normal, parasit ini tidak merugikan bagi anjing, namun bila kondisi kekebalan anjing menurun maka Demodex sp. akan berkembang menjadi lebih banyak dan menimbulkan penyakit kulit (Rather dan Hassan, 2014). Demodekosis  juga  dikenal  sebagai Red  Mange,  Follicular  Mange, Acarus Mange, kondisi anjing kasus mengalami kelainan pada kulit yang bentuknya mirip dengan penyakit  kulit  lainnya  (Sardjana,  2012).\n\nJumlah parasit tersebut bertambah banyak jika anjing mengalami penurunan sistem imun (immunodeficiency) atau dalam kondisi stress (immunosuppresif) bahkan ketika jumlahnya banyak maka dapat menyebabkan kebotakan (alopecia) dan infeksi bakteri sekunder.\n\nAnjing-anjing yang mempunyai kecenderungan immunosuppresif adalah anjing yang berada dalam lingkungan baru, anjing muda berusia di bawah 1,5 tahun, anjing yang sedang dalam pengobatan anti kanker, penggunaan kortikosteroid dosis tinggi dan jangka panjang, hyperadrenocortism, hypotyroidism dan anjing yang menderita kanker.\n\nDemodekosis terjadi sangat cepat jika sistem imun belum dewasa (anak anjing), kurang gizi, estrus dalam siklus birahi, obat-obatan (steroid) dan penyakit dalam (Henfrey, 1990; Ettinger and Feldman, 2000). Siklus hidup lengkap demodex adalah 20-30 hari pada tubuh hospes."
let penyebabBold = NSAttributedString(string: "Sistem imun (immunodeficiency) atau dalam kondisi stress (immunosuppresif). Lingkungan yang tidak baik.\n\n", attributes: [.font:UIFont.boldSystemFont(ofSize: 17)])
let demodexPenyebab: [Any] = [penyebabBold ,"Namun pada beberapa anjing, kekebalan tubuhnya tidak dapat berkembang dengan baik yang bersifat genetik. Anjing dengan kekebalan tubuh yang tidak dapat berkembang baik rentan sekali terserang tungau Demodex.\n\nDemodecosis akan sering sekali timbul. Anjing dengan kekebalan tubuh yang rendah ini biasanya tidak dianjurkan untuk dibiakkan. Penyebab utama terjadinya alopesia pada demodekosis misalnya yaitu trauma yang berhubungan dengan pruritus. Zat-zat kimia dan rangsangan fisik (mekanik) dapat memicu terjadi pruritus seperti stimulus kimiawi yang mengandung histamin."]
let gejalaBold = NSAttributedString(string: "Gejala yang ditimbulkan tergantung bentuk dan lokasi yang ditimbulkan. Diantaranya:\n\n", attributes: [.font:UIFont.boldSystemFont(ofSize: 17)])
var demodexGejala: [Any] = [gejalaBold, "1. Bentuk lokal ditandai dengan adanya alopecia yang parsial pada wajah terutama sekitar mata dan moncong anjing, juga pada daerah ekstremitas tubuh dan kulit kering yang tidak disertai rasa gatal.\n\n2. Bentuk umum ditandai dengan alopecia hampir semua bulu tubuh baik kepala, leher, lengan  dan kaki sehingga bulu menjadi jarang dan tipis dan kulit terlihat berminyak. Bentuk ini biasanya  diikuti penyakit dalam yang serius seperti tumor dan immunosuppresif."]
let dGejalaMore = "\n\nSedangkan bentuk pododermatitis dicirikan dengan alopecia kemudian kulit menjadi kering dan kasar kemudian terjadi proses hyperpigmentasi yang menyebabkan kulit menjadi merah. Pada kasus yang berat menyebabkan hewan tidak nafsu makan, kekurusan, sepsis dan kematian.\n\nMenurut Henfrey (1990), Scott et al. (2001), Triakoso (2006), Dunn (2008) gejala klinis dari demodekosis adalah pada kulit terjadi alopecia, berkerak, kemerahan, disertai rasa gatal dan sakit jika ada infeksi sekunder. Munculnya demodex biasanya pada daerah kepala, kaki depan, hidung,  daerah dada, ekor dan beberapa anjing ada juga yang terserang hanya di daerah telapak kaki dan telinga saja.\n\nPada demodekosis general, lesi terdapat hampir di seluruh tubuh dan biasanya disertai dengan infeksi sekunder. Luka atau lesi yang terjadi bermula lokal, kemudian berkembang dengan cepat pada sebagian besar tubuh hewan penderita. Anjing gelisah mengosok-gosokkan badannya yang dapat menyebabkan luka menjadi bernanah serta mengalami infeksi bakteri.\n\nBeberapa anjing agresif karena gangguan kulit yang dialaminya. Demodekosis pada hewan penderita muda cenderung lebih sering terjadi yang dimulai dari umur 3-18 bulan. Lesi yang terjadi menimbulkan rasa sakit, dapat terjadi limfadenopati dan pada kasus yang parah dapat terjadi septicaemia dan menyebabkan kematian (Belot et al., 1984; Henfrey, 1990; Scott et al. 2001)."

let metodeDiagnosa = NSAttributedString(string: "Metode Diagnosa\n\n", attributes: [.font:UIFont.boldSystemFont(ofSize: 17)])
let diagnosaBold = NSAttributedString(string: "Diagnosa hanya dapat dilakukan oleh dokter!", attributes: [.font:UIFont.boldSystemFont(ofSize: 17)])
let katarakDiagnosa: [Any] = [metodeDiagnosa, "1.  Berdasarkan gejala klinis yang muncul\n2. Berdasarkan sejarah penyakit pada anjing\n3. Berdasarkan pemeriksaan fisik\n4. Lakukan pemeriksaan laboratorium (test darah komplit dan test urin)\n5. Electroretinography test\n\n", diagnosaBold]
let demodexDiagnosa: [Any] = [metodeDiagnosa, "Diagnosa yang dapat dilakukan pada kasus demodekosis adalah dengan kerokan kulit yang agak dalam dari bagian tengah lesi, kemudian diberi tetesan KOH 10 % untuk diamati di bawah mikroskop. Apabila positif maka akan ditemukan parasit demodex yang bentuknya seperti wortel atau cerutu. \n\n", diagnosaBold]

let linkText = NSAttributedString(string: "Baca selanjutnya", attributes: [
    .font:UIFont.systemFont(ofSize: 17),
    .foregroundColor:UIColor(named: "Biru (Secondary)"),
    .link:"read_more"])
